name: CI

on:
  push:
    branches:
      - dev  # Exécute le workflow sur la branche principale

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      with:
        ref: dev  # Spécifie la branche à utiliser

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Version de Python à utiliser

    - name: Exécuter les tests
      run: python -m unittest discover -v

  update-branch:
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.ref == 'refs/heads/dev'

    steps:
    - name: Checkout de code
      uses: actions/checkout@v2
      with:
        ref: main  # Spécifie la branche principale

    - name: Fusionner les modifications de dev vers main
      run: |
        git merge dev
        git push
