name: CI

on:
  push:
    branches:
      - dev  # Exécute le workflow sur la branche principale

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      with:
        ref: dev  # Spécifie la branche à utiliser

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Version de Python à utiliser

    - name: Exécuter les tests
      run: |
        if ! python -m unittest discover -v; then
          git reset --hard HEAD^  # Revert to the state before the failed commit
          git checkout -b failures/$(date +%s)  # Create a new branch with a unique name
          git push origin HEAD -u  # Push the new branch to remote
        fi
