name: CI

on:
  push:
    branches:
      - dev  # Exécute le workflow sur la branche principale

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      with:
        ref: dev  # Spécifie la branche à utiliser

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Version de Python à utiliser

    - name: Exécuter les tests
      run: |
        if ! python -m unittest discover -v; then
          git checkout HEAD^  # Move to the previous commit
          git branch -D dev  # Delete the current dev branch
          git checkout -b dev  # Create a new dev branch from the previous commit
          git push origin dev -f  # Force push the new dev branch to remote
        fi
