name: CI

on:
  push:
    branches:
      - dev  # Exécute le workflow sur la branche dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      with:
        ref: dev  # Spécifie la branche à utiliser

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Version de Python à utiliser

    - name: Exécuter les tests
      run: python -m unittest discover -v

  merge_main:
    needs: test  # Attend que le job de test réussisse
    runs-on: ubuntu-latest
    if: success()  # Exécute cette étape uniquement en cas de succès du job précédent

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2
      with:
        ref: main  # Spécifie la branche à mettre à jour

    - name: Merge de main avec dev
      run: git merge --no-ff dev -m "Merge dev into main"
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
